package com.hotel.admin.query;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.math.BigDecimal;
import java.util.Date;

public class RoomAddQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.apartment_id
     *
     * @mbggenerated
     */
    private Integer apartmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.title
     *
     * @mbggenerated
     */
    @NotBlank(message = "房间标题不能为空")
    @Size(max = 18, message = "房间标题不允许超过18个字符")
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.sketch
     *
     * @mbggenerated
     */
    @NotBlank(message = "房间简述不能为空")
    @Size(max = 27, message = "房间简述不允许超过27个字符")
    private String sketch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.rent_price
     *
     * @mbggenerated
     */
    @NotNull(message = "房间租金不能为空")
    private BigDecimal rentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.deposit_price
     *
     * @mbggenerated
     */
    @NotNull(message = "房间押金不能为空")
    private BigDecimal depositPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.check_in_time
     *
     * @mbggenerated
     */
    @NotNull(message = "入住时间不能为空")
    private String checkInTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.check_out_time
     *
     * @mbggenerated
     */
    @NotNull(message = "退房时间不能为空")
    private String checkOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.address
     *
     * @mbggenerated
     */
    @Size(max = 35, message = "详细地址不允许超过16个字符")
    @NotNull(message = "详细地址不能为空")
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_password
     *
     * @mbggenerated
     */
    @Size(max = 16, message = "房间密码不允许超过16个字符")
    @NotNull(message = "房间密码不能为空")
    private String roomPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.description
     *
     * @mbggenerated
     */
    @Size(max = 500, message = "房间描述不允许超过500个字符")
    @NotNull(message = "房间描述不能为空")
    private String description;

    private Integer deleted;

    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.apartment_id
     *
     * @return the value of room.apartment_id
     * @mbggenerated
     */
    public Integer getApartmentId() {
        return apartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.apartment_id
     *
     * @param apartmentId the value for room.apartment_id
     * @mbggenerated
     */
    public void setApartmentId(Integer apartmentId) {
        this.apartmentId = apartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.title
     *
     * @return the value of room.title
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.title
     *
     * @param title the value for room.title
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.sketch
     *
     * @return the value of room.sketch
     * @mbggenerated
     */
    public String getSketch() {
        return sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.sketch
     *
     * @param sketch the value for room.sketch
     * @mbggenerated
     */
    public void setSketch(String sketch) {
        this.sketch = sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.rent_price
     *
     * @return the value of room.rent_price
     * @mbggenerated
     */
    public BigDecimal getRentPrice() {
        return rentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.rent_price
     *
     * @param rentPrice the value for room.rent_price
     * @mbggenerated
     */
    public void setRentPrice(BigDecimal rentPrice) {
        this.rentPrice = rentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.deposit_price
     *
     * @return the value of room.deposit_price
     * @mbggenerated
     */
    public BigDecimal getDepositPrice() {
        return depositPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.deposit_price
     *
     * @param depositPrice the value for room.deposit_price
     * @mbggenerated
     */
    public void setDepositPrice(BigDecimal depositPrice) {
        this.depositPrice = depositPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.check_in_time
     *
     * @return the value of room.check_in_time
     * @mbggenerated
     */
    public String getCheckInTime() {
        return checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.check_in_time
     *
     * @param checkInTime the value for room.check_in_time
     * @mbggenerated
     */
    public void setCheckInTime(String checkInTime) {
        this.checkInTime = checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.check_out_time
     *
     * @return the value of room.check_out_time
     * @mbggenerated
     */
    public String getCheckOutTime() {
        return checkOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.check_out_time
     *
     * @param checkOutTime the value for room.check_out_time
     * @mbggenerated
     */
    public void setCheckOutTime(String checkOutTime) {
        this.checkOutTime = checkOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.address
     *
     * @return the value of room.address
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.address
     *
     * @param address the value for room.address
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_password
     *
     * @return the value of room.room_password
     * @mbggenerated
     */
    public String getRoomPassword() {
        return roomPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_password
     *
     * @param roomPassword the value for room.room_password
     * @mbggenerated
     */
    public void setRoomPassword(String roomPassword) {
        this.roomPassword = roomPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.created_at
     *
     * @return the value of room.created_at
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.created_at
     *
     * @param createdAt the value for room.created_at
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.updated_at
     *
     * @return the value of room.updated_at
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.updated_at
     *
     * @param updatedAt the value for room.updated_at
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.status
     *
     * @return the value of room.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.status
     *
     * @param status the value for room.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.description
     *
     * @return the value of room.description
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.description
     *
     * @param description the value for room.description
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }


    Integer[] settingIds;
    Integer[] specItemIds;
    String[] imagesIds;

    public Integer[] getSettingIds() {
        return settingIds;
    }

    public void setSettingIds(Integer[] settingIds) {
        this.settingIds = settingIds;
    }

    public Integer[] getSpecItemIds() {
        return specItemIds;
    }

    public void setSpecItemIds(Integer[] specItemIds) {
        this.specItemIds = specItemIds;
    }

    public String[] getImagesIds() {
        return imagesIds;
    }

    public void setImagesIds(String[] imagesIds) {
        this.imagesIds = imagesIds;
    }
}
