package com.hotel.model.mapper;

import com.hotel.model.Apartment;
import com.hotel.model.ApartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    int countByExample(ApartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    int deleteByExample(ApartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    int insert(Apartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    int insertSelective(Apartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    List<Apartment> selectByExample(ApartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    Apartment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Apartment record, @Param("example") ApartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Apartment record, @Param("example") ApartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Apartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Apartment record);
}