package com.hotel.model.mapper;

import com.hotel.model.PackageOrder;
import com.hotel.model.PackageOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PackageOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    int countByExample(PackageOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    int deleteByExample(PackageOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    int insert(PackageOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    int insertSelective(PackageOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    List<PackageOrder> selectByExample(PackageOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    PackageOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PackageOrder record, @Param("example") PackageOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PackageOrder record, @Param("example") PackageOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PackageOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PackageOrder record);
}