package com.hotel.model.mapper;

import com.hotel.model.RoomOrder;
import com.hotel.model.RoomOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int countByExample(RoomOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int deleteByExample(RoomOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int insert(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int insertSelective(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    List<RoomOrder> selectByExample(RoomOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    RoomOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoomOrder record, @Param("example") RoomOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoomOrder record, @Param("example") RoomOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomOrder record);
}