package com.hotel.model.mapper;

import com.hotel.model.RoomImages;
import com.hotel.model.RoomImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int countByExample(RoomImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int deleteByExample(RoomImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int insert(RoomImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int insertSelective(RoomImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    List<RoomImages> selectByExampleWithBLOBs(RoomImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    List<RoomImages> selectByExample(RoomImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    RoomImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoomImages record, @Param("example") RoomImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") RoomImages record, @Param("example") RoomImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoomImages record, @Param("example") RoomImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(RoomImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomImages record);
}