package com.hotel.model.mapper;

import com.hotel.model.RoomSetting;
import com.hotel.model.RoomSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    int countByExample(RoomSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    int deleteByExample(RoomSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    int insert(RoomSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    int insertSelective(RoomSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    List<RoomSetting> selectByExample(RoomSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    RoomSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoomSetting record, @Param("example") RoomSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoomSetting record, @Param("example") RoomSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomSetting record);
}