package com.hotel.model.mapper;

import com.hotel.model.RoomSettingMapping;
import com.hotel.model.RoomSettingMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomSettingMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    int countByExample(RoomSettingMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    int deleteByExample(RoomSettingMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    int insert(RoomSettingMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    int insertSelective(RoomSettingMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    List<RoomSettingMapping> selectByExample(RoomSettingMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    RoomSettingMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoomSettingMapping record, @Param("example") RoomSettingMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoomSettingMapping record, @Param("example") RoomSettingMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoomSettingMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_setting_mapping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoomSettingMapping record);
}