package com.hotel.model.mapper;

import com.hotel.model.SecPermission;
import com.hotel.model.SecPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    int countByExample(SecPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    int deleteByExample(SecPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    int insert(SecPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    int insertSelective(SecPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    List<SecPermission> selectByExample(SecPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    SecPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SecPermission record, @Param("example") SecPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SecPermission record, @Param("example") SecPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SecPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SecPermission record);
}