package com.hotel.model.mapper;

import com.hotel.model.SecRole;
import com.hotel.model.SecRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    int countByExample(SecRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    int deleteByExample(SecRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    int insert(SecRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    int insertSelective(SecRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    List<SecRole> selectByExample(SecRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    SecRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SecRole record, @Param("example") SecRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SecRole record, @Param("example") SecRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SecRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SecRole record);
}