package com.hotel.model.mapper;

import com.hotel.model.SmsCode;
import com.hotel.model.SmsCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int countByExample(SmsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int deleteByExample(SmsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int insert(SmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int insertSelective(SmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    List<SmsCode> selectByExample(SmsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    SmsCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SmsCode record, @Param("example") SmsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SmsCode record, @Param("example") SmsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmsCode record);
}