package com.hotel.model.mapper;

import com.hotel.model.WxFormId;
import com.hotel.model.WxFormIdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxFormIdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    int countByExample(WxFormIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    int deleteByExample(WxFormIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    int insert(WxFormId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    int insertSelective(WxFormId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    List<WxFormId> selectByExample(WxFormIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    WxFormId selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WxFormId record, @Param("example") WxFormIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WxFormId record, @Param("example") WxFormIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WxFormId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_form_id
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WxFormId record);
}