package com.hotel.model;

import java.io.Serializable;
import java.util.Date;

public class PackageTimeSetting implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_time_setting.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_time_setting.package_id
     *
     * @mbggenerated
     */
    private Integer packageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_time_setting.month
     *
     * @mbggenerated
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_time_setting.weekdays
     *
     * @mbggenerated
     */
    private String weekdays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_time_setting.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_time_setting.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_time_setting.time_space
     *
     * @mbggenerated
     */
    private Integer timeSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_time_setting.limit_number
     *
     * @mbggenerated
     */
    private Integer limitNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_time_setting.occupy_number
     *
     * @mbggenerated
     */
    private Integer occupyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_time_setting.store_id
     *
     * @mbggenerated
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table package_time_setting
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_time_setting.id
     *
     * @return the value of package_time_setting.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_time_setting.id
     *
     * @param id the value for package_time_setting.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_time_setting.package_id
     *
     * @return the value of package_time_setting.package_id
     *
     * @mbggenerated
     */
    public Integer getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_time_setting.package_id
     *
     * @param packageId the value for package_time_setting.package_id
     *
     * @mbggenerated
     */
    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_time_setting.month
     *
     * @return the value of package_time_setting.month
     *
     * @mbggenerated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_time_setting.month
     *
     * @param month the value for package_time_setting.month
     *
     * @mbggenerated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_time_setting.weekdays
     *
     * @return the value of package_time_setting.weekdays
     *
     * @mbggenerated
     */
    public String getWeekdays() {
        return weekdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_time_setting.weekdays
     *
     * @param weekdays the value for package_time_setting.weekdays
     *
     * @mbggenerated
     */
    public void setWeekdays(String weekdays) {
        this.weekdays = weekdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_time_setting.start_time
     *
     * @return the value of package_time_setting.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_time_setting.start_time
     *
     * @param startTime the value for package_time_setting.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_time_setting.end_time
     *
     * @return the value of package_time_setting.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_time_setting.end_time
     *
     * @param endTime the value for package_time_setting.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_time_setting.time_space
     *
     * @return the value of package_time_setting.time_space
     *
     * @mbggenerated
     */
    public Integer getTimeSpace() {
        return timeSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_time_setting.time_space
     *
     * @param timeSpace the value for package_time_setting.time_space
     *
     * @mbggenerated
     */
    public void setTimeSpace(Integer timeSpace) {
        this.timeSpace = timeSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_time_setting.limit_number
     *
     * @return the value of package_time_setting.limit_number
     *
     * @mbggenerated
     */
    public Integer getLimitNumber() {
        return limitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_time_setting.limit_number
     *
     * @param limitNumber the value for package_time_setting.limit_number
     *
     * @mbggenerated
     */
    public void setLimitNumber(Integer limitNumber) {
        this.limitNumber = limitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_time_setting.occupy_number
     *
     * @return the value of package_time_setting.occupy_number
     *
     * @mbggenerated
     */
    public Integer getOccupyNumber() {
        return occupyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_time_setting.occupy_number
     *
     * @param occupyNumber the value for package_time_setting.occupy_number
     *
     * @mbggenerated
     */
    public void setOccupyNumber(Integer occupyNumber) {
        this.occupyNumber = occupyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_time_setting.store_id
     *
     * @return the value of package_time_setting.store_id
     *
     * @mbggenerated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_time_setting.store_id
     *
     * @param storeId the value for package_time_setting.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_time_setting
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", packageId=").append(packageId);
        sb.append(", month=").append(month);
        sb.append(", weekdays=").append(weekdays);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", timeSpace=").append(timeSpace);
        sb.append(", limitNumber=").append(limitNumber);
        sb.append(", occupyNumber=").append(occupyNumber);
        sb.append(", storeId=").append(storeId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}