package com.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Package implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.sketch
     *
     * @mbggenerated
     */
    private String sketch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.banner_image
     *
     * @mbggenerated
     */
    private String bannerImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.config
     *
     * @mbggenerated
     */
    private String config;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.special_price
     *
     * @mbggenerated
     */
    private BigDecimal specialPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.publish_status
     *
     * @mbggenerated
     */
    private Integer publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table package
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.id
     *
     * @return the value of package.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.id
     *
     * @param id the value for package.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.name
     *
     * @return the value of package.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.name
     *
     * @param name the value for package.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.sketch
     *
     * @return the value of package.sketch
     *
     * @mbggenerated
     */
    public String getSketch() {
        return sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.sketch
     *
     * @param sketch the value for package.sketch
     *
     * @mbggenerated
     */
    public void setSketch(String sketch) {
        this.sketch = sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.banner_image
     *
     * @return the value of package.banner_image
     *
     * @mbggenerated
     */
    public String getBannerImage() {
        return bannerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.banner_image
     *
     * @param bannerImage the value for package.banner_image
     *
     * @mbggenerated
     */
    public void setBannerImage(String bannerImage) {
        this.bannerImage = bannerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.config
     *
     * @return the value of package.config
     *
     * @mbggenerated
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.config
     *
     * @param config the value for package.config
     *
     * @mbggenerated
     */
    public void setConfig(String config) {
        this.config = config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.price
     *
     * @return the value of package.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.price
     *
     * @param price the value for package.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.special_price
     *
     * @return the value of package.special_price
     *
     * @mbggenerated
     */
    public BigDecimal getSpecialPrice() {
        return specialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.special_price
     *
     * @param specialPrice the value for package.special_price
     *
     * @mbggenerated
     */
    public void setSpecialPrice(BigDecimal specialPrice) {
        this.specialPrice = specialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.publish_status
     *
     * @return the value of package.publish_status
     *
     * @mbggenerated
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.publish_status
     *
     * @param publishStatus the value for package.publish_status
     *
     * @mbggenerated
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.created_at
     *
     * @return the value of package.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.created_at
     *
     * @param createdAt the value for package.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.updated_at
     *
     * @return the value of package.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.updated_at
     *
     * @param updatedAt the value for package.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.description
     *
     * @return the value of package.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.description
     *
     * @param description the value for package.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", sketch=").append(sketch);
        sb.append(", bannerImage=").append(bannerImage);
        sb.append(", config=").append(config);
        sb.append(", price=").append(price);
        sb.append(", specialPrice=").append(specialPrice);
        sb.append(", publishStatus=").append(publishStatus);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}