package com.hotel.model;

import java.io.Serializable;
import java.util.Date;

public class RoomSpecsItem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_item.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_item.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_item.specs_id
     *
     * @mbggenerated
     */
    private Integer specsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_item.specs_name
     *
     * @mbggenerated
     */
    private String specsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_item.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_item.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_specs_item
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_item.id
     *
     * @return the value of room_specs_item.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_item.id
     *
     * @param id the value for room_specs_item.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_item.name
     *
     * @return the value of room_specs_item.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_item.name
     *
     * @param name the value for room_specs_item.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_item.specs_id
     *
     * @return the value of room_specs_item.specs_id
     *
     * @mbggenerated
     */
    public Integer getSpecsId() {
        return specsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_item.specs_id
     *
     * @param specsId the value for room_specs_item.specs_id
     *
     * @mbggenerated
     */
    public void setSpecsId(Integer specsId) {
        this.specsId = specsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_item.specs_name
     *
     * @return the value of room_specs_item.specs_name
     *
     * @mbggenerated
     */
    public String getSpecsName() {
        return specsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_item.specs_name
     *
     * @param specsName the value for room_specs_item.specs_name
     *
     * @mbggenerated
     */
    public void setSpecsName(String specsName) {
        this.specsName = specsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_item.created_at
     *
     * @return the value of room_specs_item.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_item.created_at
     *
     * @param createdAt the value for room_specs_item.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_item.updated_at
     *
     * @return the value of room_specs_item.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_item.updated_at
     *
     * @param updatedAt the value for room_specs_item.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_specs_item
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", specsId=").append(specsId);
        sb.append(", specsName=").append(specsName);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}