package com.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RoomOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.order_sn
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.id_no
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.room_id
     *
     * @mbggenerated
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.room_name
     *
     * @mbggenerated
     */
    private String roomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.check_in_time
     *
     * @mbggenerated
     */
    private Date checkInTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.check_out_time
     *
     * @mbggenerated
     */
    private Date checkOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.rent_price
     *
     * @mbggenerated
     */
    private BigDecimal rentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.real_pay_rent_price
     *
     * @mbggenerated
     */
    private BigDecimal realPayRentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.deposit_price
     *
     * @mbggenerated
     */
    private BigDecimal depositPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.real_pay_deposit_price
     *
     * @mbggenerated
     */
    private BigDecimal realPayDepositPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.count_day
     *
     * @mbggenerated
     */
    private Integer countDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.pay_status
     *
     * @mbggenerated
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.union_id
     *
     * @mbggenerated
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_order.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.id
     *
     * @return the value of room_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.id
     *
     * @param id the value for room_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.order_sn
     *
     * @return the value of room_order.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.order_sn
     *
     * @param orderSn the value for room_order.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.name
     *
     * @return the value of room_order.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.name
     *
     * @param name the value for room_order.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.mobile
     *
     * @return the value of room_order.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.mobile
     *
     * @param mobile the value for room_order.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.id_no
     *
     * @return the value of room_order.id_no
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.id_no
     *
     * @param idNo the value for room_order.id_no
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.room_id
     *
     * @return the value of room_order.room_id
     *
     * @mbggenerated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.room_id
     *
     * @param roomId the value for room_order.room_id
     *
     * @mbggenerated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.room_name
     *
     * @return the value of room_order.room_name
     *
     * @mbggenerated
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.room_name
     *
     * @param roomName the value for room_order.room_name
     *
     * @mbggenerated
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.status
     *
     * @return the value of room_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.status
     *
     * @param status the value for room_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.check_in_time
     *
     * @return the value of room_order.check_in_time
     *
     * @mbggenerated
     */
    public Date getCheckInTime() {
        return checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.check_in_time
     *
     * @param checkInTime the value for room_order.check_in_time
     *
     * @mbggenerated
     */
    public void setCheckInTime(Date checkInTime) {
        this.checkInTime = checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.check_out_time
     *
     * @return the value of room_order.check_out_time
     *
     * @mbggenerated
     */
    public Date getCheckOutTime() {
        return checkOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.check_out_time
     *
     * @param checkOutTime the value for room_order.check_out_time
     *
     * @mbggenerated
     */
    public void setCheckOutTime(Date checkOutTime) {
        this.checkOutTime = checkOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.rent_price
     *
     * @return the value of room_order.rent_price
     *
     * @mbggenerated
     */
    public BigDecimal getRentPrice() {
        return rentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.rent_price
     *
     * @param rentPrice the value for room_order.rent_price
     *
     * @mbggenerated
     */
    public void setRentPrice(BigDecimal rentPrice) {
        this.rentPrice = rentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.real_pay_rent_price
     *
     * @return the value of room_order.real_pay_rent_price
     *
     * @mbggenerated
     */
    public BigDecimal getRealPayRentPrice() {
        return realPayRentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.real_pay_rent_price
     *
     * @param realPayRentPrice the value for room_order.real_pay_rent_price
     *
     * @mbggenerated
     */
    public void setRealPayRentPrice(BigDecimal realPayRentPrice) {
        this.realPayRentPrice = realPayRentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.deposit_price
     *
     * @return the value of room_order.deposit_price
     *
     * @mbggenerated
     */
    public BigDecimal getDepositPrice() {
        return depositPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.deposit_price
     *
     * @param depositPrice the value for room_order.deposit_price
     *
     * @mbggenerated
     */
    public void setDepositPrice(BigDecimal depositPrice) {
        this.depositPrice = depositPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.real_pay_deposit_price
     *
     * @return the value of room_order.real_pay_deposit_price
     *
     * @mbggenerated
     */
    public BigDecimal getRealPayDepositPrice() {
        return realPayDepositPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.real_pay_deposit_price
     *
     * @param realPayDepositPrice the value for room_order.real_pay_deposit_price
     *
     * @mbggenerated
     */
    public void setRealPayDepositPrice(BigDecimal realPayDepositPrice) {
        this.realPayDepositPrice = realPayDepositPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.count_day
     *
     * @return the value of room_order.count_day
     *
     * @mbggenerated
     */
    public Integer getCountDay() {
        return countDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.count_day
     *
     * @param countDay the value for room_order.count_day
     *
     * @mbggenerated
     */
    public void setCountDay(Integer countDay) {
        this.countDay = countDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.pay_status
     *
     * @return the value of room_order.pay_status
     *
     * @mbggenerated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.pay_status
     *
     * @param payStatus the value for room_order.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.open_id
     *
     * @return the value of room_order.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.open_id
     *
     * @param openId the value for room_order.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.union_id
     *
     * @return the value of room_order.union_id
     *
     * @mbggenerated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.union_id
     *
     * @param unionId the value for room_order.union_id
     *
     * @mbggenerated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.created_at
     *
     * @return the value of room_order.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.created_at
     *
     * @param createdAt the value for room_order.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_order.updated_at
     *
     * @return the value of room_order.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_order.updated_at
     *
     * @param updatedAt the value for room_order.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", name=").append(name);
        sb.append(", mobile=").append(mobile);
        sb.append(", idNo=").append(idNo);
        sb.append(", roomId=").append(roomId);
        sb.append(", roomName=").append(roomName);
        sb.append(", status=").append(status);
        sb.append(", checkInTime=").append(checkInTime);
        sb.append(", checkOutTime=").append(checkOutTime);
        sb.append(", rentPrice=").append(rentPrice);
        sb.append(", realPayRentPrice=").append(realPayRentPrice);
        sb.append(", depositPrice=").append(depositPrice);
        sb.append(", realPayDepositPrice=").append(realPayDepositPrice);
        sb.append(", countDay=").append(countDay);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", openId=").append(openId);
        sb.append(", unionId=").append(unionId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}