package com.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Room implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.apartment_id
     *
     * @mbggenerated
     */
    private Integer apartmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.sketch
     *
     * @mbggenerated
     */
    private String sketch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.rent_price
     *
     * @mbggenerated
     */
    private BigDecimal rentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.deposit_price
     *
     * @mbggenerated
     */
    private BigDecimal depositPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.check_in_time
     *
     * @mbggenerated
     */
    private String checkInTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.check_out_time
     *
     * @mbggenerated
     */
    private String checkOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.room_password
     *
     * @mbggenerated
     */
    private String roomPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.apartment_id
     *
     * @return the value of room.apartment_id
     *
     * @mbggenerated
     */
    public Integer getApartmentId() {
        return apartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.apartment_id
     *
     * @param apartmentId the value for room.apartment_id
     *
     * @mbggenerated
     */
    public void setApartmentId(Integer apartmentId) {
        this.apartmentId = apartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.title
     *
     * @return the value of room.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.title
     *
     * @param title the value for room.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.sketch
     *
     * @return the value of room.sketch
     *
     * @mbggenerated
     */
    public String getSketch() {
        return sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.sketch
     *
     * @param sketch the value for room.sketch
     *
     * @mbggenerated
     */
    public void setSketch(String sketch) {
        this.sketch = sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.rent_price
     *
     * @return the value of room.rent_price
     *
     * @mbggenerated
     */
    public BigDecimal getRentPrice() {
        return rentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.rent_price
     *
     * @param rentPrice the value for room.rent_price
     *
     * @mbggenerated
     */
    public void setRentPrice(BigDecimal rentPrice) {
        this.rentPrice = rentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.deposit_price
     *
     * @return the value of room.deposit_price
     *
     * @mbggenerated
     */
    public BigDecimal getDepositPrice() {
        return depositPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.deposit_price
     *
     * @param depositPrice the value for room.deposit_price
     *
     * @mbggenerated
     */
    public void setDepositPrice(BigDecimal depositPrice) {
        this.depositPrice = depositPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.check_in_time
     *
     * @return the value of room.check_in_time
     *
     * @mbggenerated
     */
    public String getCheckInTime() {
        return checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.check_in_time
     *
     * @param checkInTime the value for room.check_in_time
     *
     * @mbggenerated
     */
    public void setCheckInTime(String checkInTime) {
        this.checkInTime = checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.check_out_time
     *
     * @return the value of room.check_out_time
     *
     * @mbggenerated
     */
    public String getCheckOutTime() {
        return checkOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.check_out_time
     *
     * @param checkOutTime the value for room.check_out_time
     *
     * @mbggenerated
     */
    public void setCheckOutTime(String checkOutTime) {
        this.checkOutTime = checkOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.address
     *
     * @return the value of room.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.address
     *
     * @param address the value for room.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.room_password
     *
     * @return the value of room.room_password
     *
     * @mbggenerated
     */
    public String getRoomPassword() {
        return roomPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.room_password
     *
     * @param roomPassword the value for room.room_password
     *
     * @mbggenerated
     */
    public void setRoomPassword(String roomPassword) {
        this.roomPassword = roomPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.created_at
     *
     * @return the value of room.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.created_at
     *
     * @param createdAt the value for room.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.updated_at
     *
     * @return the value of room.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.updated_at
     *
     * @param updatedAt the value for room.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.status
     *
     * @return the value of room.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.status
     *
     * @param status the value for room.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.deleted
     *
     * @return the value of room.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.deleted
     *
     * @param deleted the value for room.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.description
     *
     * @return the value of room.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.description
     *
     * @param description the value for room.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", apartmentId=").append(apartmentId);
        sb.append(", title=").append(title);
        sb.append(", sketch=").append(sketch);
        sb.append(", rentPrice=").append(rentPrice);
        sb.append(", depositPrice=").append(depositPrice);
        sb.append(", checkInTime=").append(checkInTime);
        sb.append(", checkOutTime=").append(checkOutTime);
        sb.append(", address=").append(address);
        sb.append(", roomPassword=").append(roomPassword);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", status=").append(status);
        sb.append(", deleted=").append(deleted);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}