package com.hotel.model;

import java.io.Serializable;
import java.util.Date;

public class RoomSpecsMapping implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_mapping.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_mapping.room_id
     *
     * @mbggenerated
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_mapping.room_specs_id
     *
     * @mbggenerated
     */
    private Integer roomSpecsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_mapping.room_specs_item_id
     *
     * @mbggenerated
     */
    private Integer roomSpecsItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_mapping.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_specs_mapping.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_specs_mapping
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_mapping.id
     *
     * @return the value of room_specs_mapping.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_mapping.id
     *
     * @param id the value for room_specs_mapping.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_mapping.room_id
     *
     * @return the value of room_specs_mapping.room_id
     *
     * @mbggenerated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_mapping.room_id
     *
     * @param roomId the value for room_specs_mapping.room_id
     *
     * @mbggenerated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_mapping.room_specs_id
     *
     * @return the value of room_specs_mapping.room_specs_id
     *
     * @mbggenerated
     */
    public Integer getRoomSpecsId() {
        return roomSpecsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_mapping.room_specs_id
     *
     * @param roomSpecsId the value for room_specs_mapping.room_specs_id
     *
     * @mbggenerated
     */
    public void setRoomSpecsId(Integer roomSpecsId) {
        this.roomSpecsId = roomSpecsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_mapping.room_specs_item_id
     *
     * @return the value of room_specs_mapping.room_specs_item_id
     *
     * @mbggenerated
     */
    public Integer getRoomSpecsItemId() {
        return roomSpecsItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_mapping.room_specs_item_id
     *
     * @param roomSpecsItemId the value for room_specs_mapping.room_specs_item_id
     *
     * @mbggenerated
     */
    public void setRoomSpecsItemId(Integer roomSpecsItemId) {
        this.roomSpecsItemId = roomSpecsItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_mapping.created_at
     *
     * @return the value of room_specs_mapping.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_mapping.created_at
     *
     * @param createdAt the value for room_specs_mapping.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_specs_mapping.updated_at
     *
     * @return the value of room_specs_mapping.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_specs_mapping.updated_at
     *
     * @param updatedAt the value for room_specs_mapping.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_specs_mapping
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roomId=").append(roomId);
        sb.append(", roomSpecsId=").append(roomSpecsId);
        sb.append(", roomSpecsItemId=").append(roomSpecsItemId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}